# Generated by Django 5.2.5 on 2025-08-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='district',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
